// atest.c generated by AltoDecode 
struct {
  unsigned int b0_7: 8; 
  unsigned int b8_15: 8; 
} BF0_7;
struct {
  unsigned int b0_1: 2; 
  unsigned int b2_15: 14; 
} BF0_1;
struct {
  unsigned int b0_5: 6; 
  unsigned int b6_7: 2; 
  unsigned int b8_15: 8; 
} BF6_7;
int V0; 
int V1; 
P2(  int a1){ 
    int f2 = 1; 
    int f3 = 1; 
    while ( 10 > f3 ){  // Lp9 
        int f4 = (f3 * 2) + f2; 
        f3 = f3 + 1; 
    } // Lp9 
    f2 =  ((a1[0]) & 0xff00)>>8 ; 
    f3 = (a1[0]) & 0x00ff; 
    f4 =  ((a1[1]) & 0xff00)>>8 ; 
    ((BF0_7 *) a1)->b0_7 = 2; 
    ((BF0_7 *) (a1 + 1))->b8_15 = 3; 
    ((BF0_7 *) (a1 + 2))->b0_7 = 4; 
    return;
} 
P3(  int a1){ 
    int f2 = a1; 
    if ( f2 > 0 ){  // If59 
        a1 = 7; 
    } // If59 
    switch( f2 ){  //Lookup
    case 1:  
        Ws(  "case 1" ); 
        break; 
    case 2:  
        Ws(  "case 2" ); 
        break; 
    case 13:  
        Ws(  "case 13" ); 
        break; 
    default: 
        Ws(  "case other" ); 
        break; 
    }  //sw115
    return;
} 
P4(  int a1, int a2){ 
    V0 = a1; 
    int f3 = a1 + 5; 
    if ( f3 >= a1 ){  // If137 
        f3 = f3 + 2; 
    } else {  // If137 
        a1 = f3 - V0; 
    } // If137 
    ((BF0_1 *) a2)->b0_1 = 3; 
    ((BF6_7 *) a2)->b6_7 = 0; 
    a1 = ((a2[0]) & 0x00c0)>>6; 
    return;
} 
P5(  int a1, int a2, int a3){ 
    int f4 = 0; 
    int f5 = a1 + 1; 
    int f6 = a2 + a3; 
    int f7 = V1 - f6; 
    while ( f5 <= f7 ){  // Lp181 
        f5 = f5 + a2; 
    } // Lp181
    return;
} 
P6(){ 
    Ws(  "ATest\r" ); 
    return;
} 
P7(){ 
    int  *f1 = int[ 4 ]; 
    f1[0] = 15; 
    f1[1] = 1; 
    f1[2] = 2; 
    f1[3] = 7; 
    return;
} 
